package mx.qr.sace.persistencia.entidades;

// Generated 20-ago-2015 23:36:41 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuxCarreraId generated by hbm2java
 */
@Embeddable
public class CarreraId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1101039984318529699L;
	
	private int idCarrera;
	private int idEscolaridad;
	private int idModalidad;

	public CarreraId() {
	}

	public CarreraId(int idCarrera, int idEscolaridad, int idModalidad) {
		this.idCarrera = idCarrera;
		this.idEscolaridad = idEscolaridad;
		this.idModalidad = idModalidad;
	}

	@Column(name = "id_carrera", nullable = false)
	public int getIdCarrera() {
		return this.idCarrera;
	}

	public void setIdCarrera(int idCarrera) {
		this.idCarrera = idCarrera;
	}

	@Column(name = "id_escolaridad", nullable = false)
	public int getIdEscolaridad() {
		return this.idEscolaridad;
	}

	public void setIdEscolaridad(int idEscolaridad) {
		this.idEscolaridad = idEscolaridad;
	}

	@Column(name = "id_modalidad", nullable = false)
	public int getIdModalidad() {
		return this.idModalidad;
	}

	public void setIdModalidad(int idModalidad) {
		this.idModalidad = idModalidad;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CarreraId))
			return false;
		CarreraId castOther = (CarreraId) other;

		return (this.getIdCarrera() == castOther.getIdCarrera())
				&& (this.getIdEscolaridad() == castOther.getIdEscolaridad())
				&& (this.getIdModalidad() == castOther.getIdModalidad());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCarrera();
		result = 37 * result + this.getIdEscolaridad();
		result = 37 * result + this.getIdModalidad();
		return result;
	}

}
