package mx.qr.sace.persistencia.entidades;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AuxEscolaridad generated by hbm2java
 */
@Entity
@Table(name = "c_niveles_escolaridad", catalog = "SACE_DB")
public class Escolaridad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -163164885806447819L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_nivel_escolaridad", unique = true, nullable = false)
	private int idEscolaridad;

	@Column(name = "descripcion", length = 45)
	private String descripcion;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "escolaridad")
	private Set<Carrera> carreras = new HashSet<Carrera>(0);

	public Escolaridad() {
	}
	
	public Escolaridad(int idNivelEscolaridad) {
		this();
		this.idEscolaridad = idNivelEscolaridad;
	}
	
	public Escolaridad(String descripcion, int idNivelEscolaridad) {
		this(idNivelEscolaridad);
		this.descripcion = descripcion;
	}

	public int getIdEscolaridad() {
		return this.idEscolaridad;
	}

	public void setIdEscolaridad(int idNivelEscolaridad) {
		this.idEscolaridad = idNivelEscolaridad;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<Carrera> getCarreras() {
		return carreras;
	}

	public void setCarreras(Set<Carrera> carreras) {
		this.carreras = carreras;
	}
}
