package mx.qr.sace.persistencia.entidades;

// Generated 20-ago-2015 23:36:41 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AuxGrupo generated by hbm2java
 */
@Entity
@Table(name = "grupos", catalog = "SACE_DB")
public class Grupo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2529024799768520933L;
	private short idGrupo;
	private String gruposcol;

	public Grupo() {
	}

	public Grupo(short idGrupo) {
		this.idGrupo = idGrupo;
	}

	public Grupo(short idGrupo, String gruposcol) {
		this.idGrupo = idGrupo;
		this.gruposcol = gruposcol;
	}

	@Id
	@Column(name = "id_grupo", unique = true, nullable = false)
	public short getIdGrupo() {
		return this.idGrupo;
	}

	public void setIdGrupo(short idGrupo) {
		this.idGrupo = idGrupo;
	}

	@Column(name = "gruposcol", length = 45)
	public String getGruposcol() {
		return this.gruposcol;
	}

	public void setGruposcol(String gruposcol) {
		this.gruposcol = gruposcol;
	}

}
