package mx.qr.sace.persistencia.entidades;

// Generated 20-ago-2015 23:36:41 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AuxRequisitoCarrera generated by hbm2java
 */
@Entity
@Table(name = "carreras_requisitos", catalog = "SACE_DB")
public class RequisitoCarrera implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5430300585714483631L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_carrera_requisito", unique = true, nullable = false)
	private int idCarreraRequisito;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "id_carrera", referencedColumnName = "id_carrera", nullable = false),
			@JoinColumn(name = "id_escolaridad", referencedColumnName = "id_escolaridad", nullable = false),
			@JoinColumn(name = "id_modalidad", referencedColumnName = "id_modalidad", nullable = false) })
	private Carrera carrera;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_requisito", nullable = false)
	private Requisito requisito;

	public RequisitoCarrera() {
	}

	public RequisitoCarrera(Carrera auxCarrera, Requisito auxRequisito) {
		this.carrera = auxCarrera;
		this.requisito = auxRequisito;
	}

	
	public int getIdCarreraRequisito() {
		return this.idCarreraRequisito;
	}

	public void setIdCarreraRequisito(int idCarreraRequisito) {
		this.idCarreraRequisito = idCarreraRequisito;
	}

	
	public Carrera getCarrera() {
		return this.carrera;
	}

	public void setCarrera(Carrera auxCarrera) {
		this.carrera = auxCarrera;
	}

	
	public Requisito getRequisito() {
		return this.requisito;
	}

	public void setRequisito(Requisito auxRequisito) {
		this.requisito = auxRequisito;
	}

}
