package mx.qr.sace.persistencia.entidades;

// Generated 20-ago-2015 23:36:41 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AuxRequisito generated by hbm2java
 */
@Entity
@Table(name = "c_requisitos", catalog = "SACE_DB")
public class Requisito implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5412004080155732586L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_requisito", unique = true, nullable = false)
	private int idRequisito;
	private String descripcion;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "requisito")	
	private Set<RequisitoCarrera> requisitoCarreras = new HashSet<RequisitoCarrera>(0);

	public Requisito() {
	}
	
	public Requisito(int idRequisito) {
		this.idRequisito = idRequisito;
	}

	public int getIdRequisito() {
		return this.idRequisito;
	}

	public void setIdRequisito(int idRequisito) {
		this.idRequisito = idRequisito;
	}

	@Column(name = "descripcion", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<RequisitoCarrera> getRequisitoCarreras() {
		return this.requisitoCarreras;
	}

	public void setAuxRequisitoCarreras(Set<RequisitoCarrera> requisitoCarreras) {
		this.requisitoCarreras = requisitoCarreras;
	}

}
