package mx.qr.sace.persistencia.entidades;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuxCarreraId generated by hbm2java
 */
@Embeddable
public class RespuestaId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1101039984318529699L;
	
	@Column(name = "id_respuesta", nullable = false)
	private int idRespuesta;
	
	@Column(name = "id_pregunta", nullable = false)
	private int idPregunta;

	public RespuestaId() {
	}

	public RespuestaId(int idRespuesta, int idPregunta) {
		this();
		this.idRespuesta = idRespuesta;
		this.idPregunta = idPregunta;
	}

	public int getIdRespuesta() {
		return idRespuesta;
	}

	public void setIdRespuesta(int idRespuesta) {
		this.idRespuesta = idRespuesta;
	}

	public int getIdPregunta() {
		return idPregunta;
	}

	public void setIdPregunta(int idPregunta) {
		this.idPregunta = idPregunta;
	}
}
